secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.
twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "AC1ddad3fc708a2bc602ecd88060c5caa9") %>
twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "1975dec4fdf08bdc3d9c1e6fe963d87c") %>
twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+12197322327") %>